version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  vespa:
    image: vespaengine/vespa
    hostname: vespa-container
    ports:
      - "8080:8080"
      - "19071:19071"
    volumes:
      - vespa:/opt/vespa/var
      - vespa:/opt/vespa/logs
volumes:
  db:
    driver: local
  vespa:
    driver: local
